### ISSUE TITLE
是否有计划适配 https://github.com/probe-rs/probe-rs

### ISSUE THREAD

**Issue by taotieren** [HalfSweet/HSLinkPro-Hardware#1]
是否有计划适配 https://github.com/probe-rs/probe-rs

**Comment by solosky** [comment]
这只是一个CMISS-DAP兼容的调试器，probe-rs本来就支持。

**Comment by taotieren** [comment]
hs-probe-firmware 支持 USB 2.0 HS 是否会适配 https://github.com/probe-rs/hs-probe-firmware
如果能支持的话，也方便使用 rust 的插件进行开发 https://github.com/probe-rs/vscode

**Comment by HalfSweet** [comment]
本来就原生支持probe-rs
probe-rs可以理解为gdb sever，cmsis-dap是debugger的通信兼容层；hslink是一个实现了cmsis-dap协议的硬件，hs-probe同样是一个实现了cmsis-dap的硬件；CherryDAP是一个实现cmsis-dap的软件框架。这几个概念希望能理解一下。
